export const Colors = {
  primary: '#2E7D32',
  accent: '#66BB6A',
  accentLight: '#E8F5E9',
  white: '#FFFFFF',
  background: '#FFFFFF',
  surface: '#F7F7F7',
  textPrimary: '#1A1A1A',
  textSecondary: '#757575',
  textLight: '#BDBDBD',
  border: '#EEEEEE',
  error: '#E53935',
  errorLight: '#FFEBEE',
  success: '#2E7D32',
  inputBg: '#F5F5F5',
  card: '#FFFFFF',
  tabBarBg: '#FFFFFF',
  // backward-compat aliases
  orange: '#66BB6A',
  brown: '#2E7D32',
  green: '#2E7D32',
  orangeLight: '#E8F5E9',
  brownLight: '#F0F4F0',
  greenLight: '#E8F5E9',
};
