export const Colors = {
  primary: '#1A1A1A',
  accent: '#C8A97E',
  accentLight: '#F5F0EB',
  white: '#FFFFFF',
  background: '#FFFFFF',
  surface: '#F5F0EB',
  textPrimary: '#1A1A1A',
  textSecondary: '#8A8A8A',
  textLight: '#C4C4C4',
  border: '#EBEBEB',
  error: '#E53935',
  errorLight: '#FFEBEE',
  success: '#1A1A1A',
  inputBg: '#F5F0EB',
  card: '#FFFFFF',
  tabBarBg: '#FFFFFF',
  // backward-compat aliases
  orange: '#C8A97E',
  brown: '#1A1A1A',
  green: '#1A1A1A',
  orangeLight: '#F5F0EB',
  brownLight: '#F5F0EB',
  greenLight: '#F5F0EB',
};
