export const Colors = {
  primary: '#1A2E1A',
  accent: '#E8820C',
  accentLight: '#FFF4E6',
  secondary: '#4A7C3F',
  white: '#FFFFFF',
  background: '#FFFFFF',
  surface: '#F8FAF8',
  textPrimary: '#1A2E1A',
  textSecondary: '#6B7B6B',
  textLight: '#B0BDB0',
  border: '#E8EDE8',
  error: '#E53935',
  errorLight: '#FFEBEE',
  success: '#1A2E1A',
  inputBg: '#F8FAF8',
  card: '#FFFFFF',
  tabBarBg: '#FFFFFF',
  // backward-compat aliases
  orange: '#E8820C',
  brown: '#1A2E1A',
  green: '#1A2E1A',
  orangeLight: '#FFF4E6',
  brownLight: '#F8FAF8',
  greenLight: '#F8FAF8',
};
